#!/bin/bash -x
echo ""
echo "*******************************************************"
echo "*                  Wt bootstrapper                    *"
echo "*******************************************************"
echo ""

SYSTEM=`uname -s`
if [[ $SYSTEM =~ BSD ]]; then
  DOWNLOADER="fetch -a -m"
elif [[ $SYSTEM =~ Darwin ]]; then
  DOWNLOADER="curl --retry 10 -C - -O -S"
else
  DOWNLOADER="wget -N -c"
fi

PATH_TO_SCRIPT=$(cd ${0%/*} && echo $PWD/${0##*/})
BATDIR=`dirname "$PATH_TO_SCRIPT"`
BASEDIR=$PWD
PREFIX=$BASEDIR/prefix

if [ -n $1 ] && ( [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ] )
then
  echo "Usage:" 
  echo "  $0 help | -h | --help                     This help"
  echo "  $0 fetch | -f | --fetch                   Download dependencies, do not build anything now [for later usage]"
  echo "  $0 [CMake parameters]                     Download and build Wt and its dependencies. CMake parameters are optional."
  echo "  $0 git | --git | -g [CMake parameters]    Download and build Wt and its dependencies. CMake parameters are optional."
  exit
fi

CMAKE_ZIP=cmake-2.8.12.tar.gz
CMAKE_FULLURL=http://www.cmake.org/files/v2.8/$CMAKE_ZIP
CMAKE_DIRECTORY=cmake-2.8.12

echo "Checking directories..."
[ -d downloads ] || mkdir downloads
[ -d build ] || mkdir build

echo "Downloading CMake..."
cd downloads
[ -f $CMAKE_ZIP ] || $DOWNLOADER $CMAKE_FULLURL

if [ ! -f $PREFIX/bin/cmake ]
then
  echo "Building and installing CMake..."
  tar xf $BASEDIR/downloads/$CMAKE_ZIP
  cd $CMAKE_DIRECTORY
  ./bootstrap --prefix=$PREFIX
  make
  make install
  cd ..
  rm -rf $CMAKE_DIRECTORY
fi

echo "Bootstrapping..."

if [ -n $1 ] && ( [ "$1" = "fetch" ] || [ "$1" = "--fetch" ] || [ "$1" = "-f" ] )
then
  shift
  cd $BASEDIR/build
  $PREFIX/bin/cmake -DWINST_BASEDIR:PATH=$BASEDIR -DWINST_PREFIX:PATH=$PREFIX -DFETCH_ONLY:BOOL=1 $@ $BATDIR/cmake
else

  if [ -n $1 ] && ( [ "$1" = "git" ] || [ "$1" = "--git" ] || [ "$1" = "-g" ] )
  then
    WTGIT=-DWTGIT:BOOL=1
  else
    WTGIT=-DWTGIT:BOOL=0
  fi

  if [ -f $BASEDIR/build/fetch-only ]
  then
    rm -rf $BASEDIR/build
    mkdir $BASEDIR/build
  fi

  cd $BASEDIR/build
  $PREFIX/bin/cmake -DWINST_BASEDIR_:PATH=$BASEDIR -DWINST_BATDIR_:PATH=$BATDIR -DWINST_PREFIX_:PATH=$PREFIX $WTGIT $@ $BATDIR/cmake
fi
