%3 -E make_directory "%2/postgresql/include"
%3 -E make_directory "%2/postgresql/libpq"
%3 -E make_directory "%2/postgresql/internal"

%3 -E copy "%1/src/include/postgres_ext.h" "%2/postgresql/postgres_ext.h"
%3 -E copy "%1/src/interfaces/libpq/libpq-events.h" "%2/postgresql/libpq-events.h"
%3 -E copy "%1/src/include/pg_config_ext.h" "%2/postgresql/pg_config_ext.h"
%3 -E copy "%1/src/include/pg_config.h" "%2/postgresql/pg_config.h"
%3 -E copy "%1/src/include/pg_config_manual.h" "%2/postgresql/pg_config_manual.h"
%3 -E copy "%1/src/interfaces/libpq/libpq-fe.h" "%2/postgresql/libpq-fe.h"
%3 -E copy "%1/src/include/libpq/libpq-fs.h" "%2/postgresql/libpq/libpq-fs.h"
%3 -E copy "%1/src/include/port.h" "%2/postgresql/internal/port.h"
%3 -E copy "%1/src/interfaces/libpq/pqexpbuffer.h" "%2/postgresql/internal/pqexpbuffer.h"
%3 -E copy "%1/src/include/postgres_fe.h" "%2/postgresql/internal/postgres_fe.h"
%3 -E copy "%1/src/interfaces/libpq/libpq-int.h" "%2/postgresql/internal/libpq-int.h"
%3 -E copy "%1/src/include/libpq/pqcomm.h" "%2/postgresql/internal/libpq/pqcomm.h"
%3 -E copy "%1/src/include/c.h" "%2/postgresql/internal/c.h"
%3 -E copy "%1/src/include/pg_config_os.h" "%2/postgresql/pg_config_os.h"
